### ISSUE TITLE
[Feature] Add new properties for raw values

### ISSUE THREAD

**Issue by EdmonDantes** [woodpecker-ci/plugin-git#134]
Please add properties `ssh-key-raw` to provide Base64 string of SSH key (not path to file) and `custom-cert-raw` to provide Base64 string of custom server certificate.

I tried to use this plugin in a Woodpecker with a Kubernetes backend. I can't add Docker volume to clone step, and I can't execute any command (for example to create a file). So I can not create any file and only set values to properties.
I think it will be great if a user can provide a secret value with a key to properties.

**Comment by OppOops** [comment]
Here is the suggestion to use normal git commands like this, which will need to change the ssh-key file permission and add the known_hosts in to list.
Below we suppose the git host is `github.com` :
```yaml
skip_clone: true
steps:
  - name: copy-key
    image: alpine/git
    commands:
      #if the content is base64, just decode it with base64 -d ... > pull_key
      - echo "$CLONE_SSH_KEY_CONTENT" > pull_key
      - chmod 600 pull_key
      - mkdir -p /root/.ssh
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      
      # below commands simiulate the woodpeckerci/pulgin-git
      - git init
      - git remote add origin $REMOTE_GIT_URL
      - git config core.sshCommand 'ssh -i pull_key'
      - git fetch && git checkout $PREFER_BRANCH
    secrets: [ CLONE_SSH_KEY_CONTENT ]
```
`pull_key` will leave in the default workspace. If we use `woodpeckerci/plugin-git` to fetch the repo, the `~/.ssh/known_hosts` needs to be add further.
