### ISSUE TITLE
2.6.1 isn't able to fetch git tags anymore

### ISSUE THREAD

**Issue by SourceCodeBot** [woodpecker-ci/plugin-git#205]
Hey guys,
I face some issues with 2.6.1 on woodpecker 2.8.1 and 3.1.0.
In my woodpecker.yaml I use git to identify the version of my application by describing the current tag using:

```yaml
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: Step 1
    image: docker 
    commands:
      - git tag --list
      - git describe --tags --abbrev=0
      - sh -c "echo hello world"
```

The pipeline output tells me, that no git tag is fetched and git describe run into an error. 

Is there any known bug or is someone able to help me with this issue?
I change no settings since friday, and the last build on afternoon run successfully at this step.

Pipeline output in my nutshell project:
```txt clone step
+ git init --object-format sha1 -b SourceCodeBot-patch-1
Initialized empty Git repository in /woodpecker/src/github.com/SourceCodeBot/woodpecker-ci-playground/.git/
+ git config --global --replace-all safe.directory /woodpecker/src/github.com/SourceCodeBot/woodpecker-ci-playground
+ git remote add origin https://github.com/SourceCodeBot/woodpecker-ci-playground.git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +437c46227ea30c34630f990b37763b87d3e882ff:
From https://github.com/SourceCodeBot/woodpecker-ci-playground
 * branch            437c46227ea30c34630f990b37763b87d3e882ff -> FETCH_HEAD
+ git reset --hard -q 437c46227ea30c34630f990b37763b87d3e882ff
+ git submodule update --init --recursive --depth=1 --recommend-shallow
+ git lfs fetch
fetch: Fetching reference refs/heads/SourceCodeBot-patch-1
+ git lfs checkout
```

```txt step 1
+ git tag --list
+ git describe --tags --abbrev=0
fatal: No names found, cannot describe anything.
```
