### ISSUE TITLE
Submodule override in version 2.6.4 not working with Woodpecker 2.8.3

### ISSUE THREAD

**Issue by Gr3q** [woodpecker-ci/plugin-git#238]
Clone step:

```yaml
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      recursive: true
      submodule_override:
        help-centre/help-centre-docs: https://gitea.internal.netduma.com/NetDuma/help-centre.git
```

Error received:

```
2025/05/28 15:41:47 could not parse "{\"help-centre/help-centre-docs\":\"[https://gitea.internal.netduma.com/NetDuma/help-centre.git\"}"](https://gitea.internal.netduma.com/NetDuma/help-centre.git/%22%7D%22) as map[string]string value from environment variable "PLUGIN_SUBMODULE_OVERRIDE" for flag submodule-override: item "{\"help-centre/help-centre-docs\":\"[https://gitea.internal.netduma.com/NetDuma/help-centre.git\"}"](https://gitea.internal.netduma.com/NetDuma/help-centre.git/%22%7D%22) is missing separator "="
```

Should the latest release work with Woodpecker CI pre-3 or was there a breaking change? Or am I defining the clone step wrong?
