### ISSUE TITLE
Permissions issue directory

### ISSUE THREAD

**Issue by rubenelshof** [woodpecker-ci/plugin-git#245]
I use woodpecker to lint my Ansible configuration using the below workflow:
```
labels:
  hostname: "devvy"

steps:
  lint-ansible:
    image: public.ecr.aws/docker/library/alpine:edge
    directory: ansible/
    commands:
      - apk add ansible-lint just py3-passlib openssl
      - ansible-galaxy collection install -r ../tools/ansible-requirements.yml
      - echo "$vault_password" > .vault-password
      - just lint
    environment:
      vault_password:
        from_secret: vault_password
when:
  event: [ push, manual ]
  branch: main
```

This currently fails due to permissions issue I believe was introduced in 2.6.5 (#240):
```
[WARNING]: Ansible is being run in a world writable directory
(/woodpecker/src/git.dionylabs.com/dionylabs/infrastructure/ansible), ignoring
it as an ansible.cfg source. For more information see
https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-
world-writable-dir
```

Is there a setting to change the permission from `777` to something safe like `755`?
