### ISSUE TITLE
custom clone step fails with no $HOME set in v1.5.0 and v1.6.0

### ISSUE THREAD

**Issue by okkiv** [woodpecker-ci/plugin-git#45]
After migrating to a new docker host, the clone step errors out with:

```
+ git config --global http.sslVerify false
fatal: $HOME not set
exit status 128
```

I'm using a self signed certificate and therefore in my .woodpecker.yml I have defined a custom clone step to skip ssl verification:

```
clone:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true
```

Last working tag for me is v1.4.0:
```
clone:
  clone:
    image: woodpeckerci/plugin-git:v1.4.0
    settings:
      skip_verify: true
```
