### ISSUE TITLE
Clone: "detected dubious ownership in repository"

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/plugin-git#63]
Not sure if this is the right place but I am getting the following error during cloning after a fresh install of NEXT in a kubernetes environment.

The reason is most likely that the cloning user does not match the the user owning the repo files. Yet I haven't found any report so far about this one in woodpecker and I've also not facing it in Drone. I also can't see how I can manually call the workaround before the cloning kicks in. But I must be clearly have done a mistake in my agent configuration? 

As it can be seen it's just a dummy repo with a "Hello world" YAML, nothing fancy. 

```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/<HOST>/patrick/test2/.git/
+ git remote add origin https://<HOST>/patrick/test2.git
fatal: detected dubious ownership in repository at '/woodpecker/src/<HOST>/patrick/test2'
To add an exception for this directory, call:

	git config --global --add safe.directory /woodpecker/src/<HOST>/patrick/test2
exit status 128
```

![image](https://user-images.githubusercontent.com/8430564/224275333-75fecd89-578d-4510-98d8-dd83d46e008a.png)

**Comment by pat-s** [comment]
I can see that the containers runs with user `root` and the checkout is probably happening with another user (or expecting another one). 

I wonder though that I am the first/only reporting this as I guess that multiple people use the k8s backend with `next` already?

Debugging further I see that even when adding a `safe.directory` call, running `bin/plugin-git` afterwards is not picking it up

```
+ whoami
root
+ id root
uid=0(root) gid=0(root) groups=0(root),0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
+ tail /etc/passwd
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
+ git --version
git version 2.39.0
+ git config --global --add safe.directory '*'
+ git init -b main
Initialized empty Git repository in /woodpecker/src/<HOST>/patrick/test2/.git/
+ git remote add origin https://<HOST>/patrick/test2.git
+ git config --global --add safe.directory '*'
+ /bin/plugin-git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/heads/main:
fatal: detected dubious ownership in repository at '/woodpecker/src/<HOST>/patrick/test2'
To add an exception for this directory, call:

	git config --global --add safe.directory /woodpecker/src/<HOST>/patrick/test2
exit status 128
```

Here are my values for the agent:

```yml
image:
  registry: docker.io
  repository: woodpeckerci/woodpecker-agent
  pullPolicy: Always
  tag: "next-alpine"

env:
  WOODPECKER_SERVER: woodpecker-server.woodpecker-server.svc.cluster.local:9000
  WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker-agent
  WOODPECKER_BACKEND_K8S_STORAGE_CLASS: efs-sc-woodpecker
  WOODPECKER_BACKEND: kubernetes
  WOODPECKER_BACKEND_K8S_STORAGE_RWX: true
  WOODPECKER_USERNAME: x-oauth-basic

  WOODPECKER_MAX_WORKFLOWS: 2
  WOODPECKER_DEBUG_PRETTY: true
```
