### ISSUE TITLE
"Could not resolve host" error only in `plugin-git`

### ISSUE THREAD

**Issue by ambroisie** [woodpecker-ci/plugin-git#65]
Hello :wave: 

I have the following error message during the clone step on my v0.15.6 agent:

```
git init -b main
Initialized empty Git repository in /woodpecker/src/git.belanyi.fr/ambroisie/test-drone/.git/
git remote add origin https://git.belanyi.fr/ambroisie/test-drone.git
git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/heads/main:
fatal: unable to access 'https://git.belanyi.fr/ambroisie/test-drone.git/': Could not resolve host: git.belanyi.fr
exit status 128 
```

I have tried following the [debugging steps in the FAQ](https://woodpecker-ci.org/faq#how-to-debug-clone-issues) and it works in that instance.

I also tried disabling the clone step and adding an explicit build step which runs `woodpeckerci/plugin-git`: still fails.

I tried using `drone/git` as an image for the `clone.git.image` value: this works.

So my issue seems to be specific to this plugin, as both `drone/git` and the `debian` image managed to pull the repo without any issues.

<details>
<summary>Investigation details</summary>

Running the following pipeline:

```yaml
skip_clone: true

pipeline:
  git:
    image: woodpeckerci/plugin-git
    group: clone
    commands:
      - mkdir foo
      - cd foo
      - git config --list
      - git init
      - git remote add origin https://git.belanyi.fr/ambroisie/test-drone.git 
      - "git fetch --no-tags --depth=1 origin +refs/heads/main:"
      - ls -la

  git-drone:
    image: drone/git
    group: clone
    commands:
      - mkdir bar
      - cd bar
      - git config --list
      - git init
      - git remote add origin https://git.belanyi.fr/ambroisie/test-drone.git 
      - "git fetch --no-tags --depth=1 origin +refs/heads/main:"
      - ls -la

  build:
    image: debian:stable-backports
    group: clone
    commands:
      - apt update
      - apt install -y inetutils-ping wget git
      - ping -c 4 git.belanyi.fr
      - wget git.belanyi.fr
      - mkdir foobar
      - cd foobar
      - git config --list
      - git init
      - git remote add origin https://git.belanyi.fr/ambroisie/test-drone.git 
      - "git fetch --no-tags --depth=1 origin +refs/heads/main:"
      - ls -la
```

The configuration for both `woodpeckerci/plugin-git` and  `drone/git` have `filter.lfs.*` options set, whereas `debian` is empty.

The drone plugin and debian image both successfully run the commands, while `woodpeckerci/git-plugin` fails with the same error.

</details>
