### ISSUE TITLE
Clone failed: could not read Username for '$url': No such device or address

### ISSUE THREAD

**Issue by Rubonnek** [woodpecker-ci/plugin-git#66]
**Describe the bug**

Say you have two pipelines defined where the first clones fine but takes about an hour to finish. The default clone operation fails on the second pipeline with the message:
```
fatal: could not read Username for '$url': No such device or address
```
when running against Forgejo v1.19 even when `WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true` is set.

I believe this issue is related to some timeout value on Forgejo's side since in its logs I get a `404 Unauthorized access` message.

**System Info**
The `/version` slug is not working for me against my server instance -- I'm getting a 404.

Version: next-3a475ce2
Image: docker.io/woodpeckerci/woodpecker-server:next
Hash: 09e1c0597a92

Compose file example:
```yaml
version: "3.8"
services:
  app:
    image: docker.io/woodpeckerci/woodpecker-server:next
    ports:
      - "<REDACTED>"
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=<REDACTED>
      - WOODPECKER_HOST=https://<REDACTED>
      - WOODPECKER_AGENT_SECRET=<REDACTED>
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://<REDACTED>
      - WOODPECKER_GITEA_CLIENT=<REDACTED>
      - WOODPECKER_GITEA_SECRET=<REDACTED>
      - WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
    volumes:
      - woodpecker:/var/lib/woodpecker/
volumes:
    woodpecker:
```

**Additional Context**

As a workaround I implemented my own clone step using an access token as the password instead with an alpine container. For example, cloning `https://$USER:$ACCESS_TOKEN@forgejo.example/$ORG/$REPO` works fine for me.

This is what I'm using specifically:

```yaml
skip_clone: true

pipeline:
  clone:
    image: docker.io/alpine/git:latest
    secrets:
      - source: access-token-secret
        target: ACCESS_TOKEN
    commands:
      - git init -b $$CI_COMMIT_BRANCH
      # NOTE: Replace GIT_USER on the next line
      - MODIFIED_REPO_URL=$$(printf "%s\n" "$$CI_REPO_REMOTE" | sed -e "s|https://|https://GIT_USER:$$ACCESS_TOKEN@|g")
      - git remote add origin $$MODIFIED_REPO_URL
      - git fetch --no-tags --depth=1 --filter=tree:0 origin "+$$CI_COMMIT_REF"
      - git reset --hard -q $$CI_COMMIT_SHA
      - git submodule update --init --recursive
      - git lfs fetch
      - git lfs checkout
```

**Comment by 6543** [comment]
that has something to do with the crafted netrc config ...

**Comment by 6543** [comment]
... not sure what exactly go wrong through ... based on the info you provide

**Comment by Rubonnek** [comment]
> BUT, if I remove the `clone`

Now that you mention it, I recall trying to configure the clone plugin like that and I stumbled upon the same issue.

In fact, I was able to reproduce the issue with just this:

```
clone:
  git:
    image: woodpeckerci/plugin-git:2.0.3
```

**Comment by anbraten** [comment]
Could be related to the change from #1352

**Comment by Wojnr** [comment]
> Could be related to the change from #1352

Probably it is. After rollback to docker image before this pr almost everything works again.

**Comment by Sebclem** [comment]
As a workaround, you can disable this in the repository settings, it's work for me:
![image](https://user-images.githubusercontent.com/23737709/231382094-aa6a249d-3926-45ff-8555-f6748ef44576.png)

**Comment by muradm** [comment]
@Sebclem, I have the same issue, but somehow I don't see the option you mention to disable as workaround. Why is that?

**Comment by fuskiid** [comment]
> @Sebclem, I have the same issue, but somehow I don't see the option you mention to disable as workaround. Why is that?

I had Cloudflare caching an old version on my end, I had to disable it. Could you have a similar issue? After fixing that on docker container version `next-9b32d021b3` I now see the option.

**Comment by patrickuhlmann** [comment]
I do have the same issue. One thing I noticed is that it seems to work fine if only one pipeline is run at a time (which means that they can start immediately). As soon as jobs are queuing (which means that they start delayed) they run into this problem. I disabled (unchecked) "Only inject netrc credentials into trusted containers but it still doesn't work.

I am also using the next version and my step is configured like that:
```
clone:
  git:
    image: woodpeckerci/plugin-git
    environment:
      - PLUGIN_LFS=false
      - PLUGIN_SKIP_VERIFY=true
```

**Comment by patrickuhlmann** [comment]
> ... not sure what exactly go wrong through ... based on the info you provide

what info would be useful to provide?

**Comment by pat-s** [comment]
Unchecking `"Only inject netrc credentials into trusted containers"` worked for me.

**Comment by patrickuhlmann** [comment]
I found this issue today by coincidence: https://github.com/gitkraken/vscode-gitlens/issues/1027. They report to having this problem when using HTTPS instead of SSH. I then saw in the log ```git remote add origin https://forgejo.***.ch/***/***.git```. Maybe switching to SSH would make it more stable?

**Comment by lafriks** [comment]
> Maybe switching to SSH would make it more stable?

you can use ssh only with users ssh key and woodpecker does not have it and should not have it either so that's not really an option

**Comment by pat-s** [comment]
> Unchecking "Only inject netrc credentials into trusted containers" worked for me.

I wonder if this should be the default given how many people seem to face issues with it. And not all of them will arrive here and read through this issue?

**Comment by lafriks** [comment]
As this is only in development version and 1.0 will be breaking anyway, it's better to use secure by default

**Comment by patrickuhlmann** [comment]
> > Unchecking "Only inject netrc credentials into trusted containers" worked for me.
> 
> I wonder if this should be the default given how many people seem to face issues with it. And not all of them will arrive here and read through this issue?

I still have the issue even when I uncheck the option. Doesn't seem to be a "reliable workaround".

**Comment by pat-s** [comment]
@patrickuhlmann Do you still face this error with the latest plugin version and latest WP server? If so, could you post your setup in more detail and also what repo options are enabled/disabled?

**Comment by patrickuhlmann** [comment]
I updated all components and still face the same issue.

I run everything in docker containers on a Synology Diskstation. I have the following containers:
- codeberg/forgejo/forgejo:1.20
- woodpeckerci/woodpecker-server:v1.0.4
- woodpecker/woodpecker-agent:v1.0.4 (first runner)
- woodpecker/woodpecker-agent:v1.0.4 (second runner)

The error happens when I run renovate. This job is running more than one hours and occupies one runner. It creates many pull requests which in turn trigger builds on other repositories. These builds are running on the second runner. In the beginning everything works fine. After a while (when lots of jobs are queued up) they start to fail. 

The job output is always like this:
```
+ git config --global http.sslCAInfo /opt/MyLAN.crt
+ git init -b master
Initialized empty Git repository in /woodpecker/src/forgejo.me.ch/My/repo.git/
+ git remote add origin https://forgejo.me.ch/My/repo.git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/pull/108/head:
fatal: could not read Username for 'https://forgejo.me.ch': No such device or address
exit status 128
```

All pipelines are similar. For example
```
clone:
  git:
    image: woodpeckerci/plugin-git
    environment:
      - PLUGIN_LFS=false
      - PLUGIN_CUSTOM_SSL_PATH=/opt/MeLAN.crt
    volumes:
      - /volume1/docker/woodpecker/MeLAN.crt:/opt/MeLAN.crt

pipeline:
  verify:
    image: gradle:8.1.0-jdk17-focal
    commands:
    - gradle assemble
    - gradle check
    volumes:
    - /volume1/docker/woodpecker/gradle:/root/.gradle
```

In the forgejo log I see
```
..rvices/auth/basic.go:130:Verify() [E] UserSignIn: user's password is invalid [uid: 1, name: patrick]
...s/auth/middleware.go:23:func1() [E] Failed to verify user: user's password is invalid [uid: 1, name: patrick]
 ...eb/routing/logger.go:102:func1() [I] router: completed GET /My/repo.git/info/refs?service=git-upload-pack for 172.17.0.9:0, 401 Unauthorized in 80.4ms @ auth/middleware.go:20(auth.Auth)
```

In the runner I see
```
ERR grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Step finished with exit code 1,  | error=rpc error: code = Unknown desc = Step finished with exit code 1, 
WRN cancel signal received | repo=My/repo pipeline=104 id=3156 error=rpc error: code = Unknown desc = Step finished with exit code 1, 
```

In the woodpecker logs, I see
```
 ip=172.17.0.3 latency=12411.027311 method=POST path=/hook status=500 user-agent=Go-http-client/1.1
ERR failure to save pipeline for My/repo | error=database is locked
ERR error=Error #01: failure to save pipeline for My/repo
```
