### ISSUE TITLE
Could not resolve host — only in clone stage

### ISSUE THREAD

**Issue by BinarySpike** [woodpecker-ci/plugin-git#68]
I am having an issue similar to #65

I have two debian servers, each with docker installed.  The first hosts my gitea server, the second hosts woodpecker-ci.  Both as docker containers.  I have a DNS appliance with resolutions for both my debian servers (prime & automation).

When a pipeline tries to clone from my gitea servers, I get the below error
```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/prime/nathan/complaintio/.git/
+ git remote add origin http://prime/nathan/complaintio.git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/heads/main:
fatal: unable to access 'http://prime/nathan/complaintio.git/': Could not resolve host: prime
exit status 128
```

However, the below pipeline pings just fine:
```
clone:
  noop:
    image: busybox

pipeline:
  nettest:
    image: busybox
    commands:
      - ping -c 3 prime
  build:
    image: node
    commands:
    - yarn
    - cd complaintioapp
    - yarn
    - yarn build
```
```
+ ping -c 3 prime
PING prime (192.168.1.210): 56 data bytes
64 bytes from 192.168.1.210: seq=0 ttl=63 time=0.506 ms
64 bytes from 192.168.1.210: seq=1 ttl=63 time=0.441 ms
64 bytes from 192.168.1.210: seq=2 ttl=63 time=0.431 ms

--- prime ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.431/0.459/0.506 ms
```

Unlike #65 `drone/git` gives the same error in this case.

**Why would the clone step fail to resolve intranet DNS?**

<details>
<summary>Woodpecker Docker Compose file</summary>

```
version: "3"

networks:
  automation:
    external: false

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    ports:
      - 80:8000
    volumes:
      - /shared/woodpecker/:/var/lib/woodpecker/
    networks:
      - automation
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://automation:80
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://prime:80
      - WOODPECKER_GITEA_CLIENT=-snip
      - WOODPECKER_GITEA_SECRET=-snip-
      - WOODPECKER_ADMIN=root
      - WOODPECKER_SECRET=-snip-
      - WOODPECKER_AGENT_SECRET=-snip-

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    networks:
      - automation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
	environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_SECRET=-snip-
      - WOODPECKER_AGENT_SECRET=-snip-
      - WOODPECKER_LOG_LEVEL=trace
      - WOODPECKER_BACKEND=docker
```
</details>
